### ISSUE TITLE
Virtual keyboard: Cannot press same button twice inside Angular/Quill project (clicked buttons become sticky / are not released)

### ISSUE THREAD

**Issue by anisabboud** [arnog/mathlive#1935]
## Description

I use mathlive inside a Quill editor in an Angular project - see https://github.com/arnog/mathlive/issues/1476.

After upgrading from v0.89 to v0.90/v0.92, the virtual keyboard isn't functioning properly like before.

If I click the same button twice, the first click works fine, but the second click doesn't work - it's like the key isn't being released once it's clicked (as if it stays pressed down).
For example: Typing 123 via the virtual keyboard works fine, but typing 555 isn't possible. See the video below for a demonstration:
![2023-04-19 mathlive sticky buttons](https://user-images.githubusercontent.com/5672108/233084462-68ee17c7-60fd-40ff-947d-396e843424d8.gif)

---

On desktop, there are no console errors accompanying the issue. But when simulating a mobile device via Chrome devtools, a console error is thrown when a button is clicked for the second time. For example, trying to type "9877": `Uncaught DOMException: Failed to execute 'releasePointerCapture' on 'Element': No active pointer with the given id is found.`
![2023-04-19 mathlive sticky buttons mobile](https://user-images.githubusercontent.com/5672108/233086679-625c7b90-9999-4f1a-99ce-9f414eda7e3d.gif)

---

This issue does not happen on your [live demo](https://cortexjs.io/mathlive/), so it probably has to do with mathlive being wrapped inside Quill/Angular. 
I will try to debug this further/isolate the issue, but I would appreciate if you had any tips/hints on what has changed with regards to the virtual keyboard button presses in v0.90 that could be causing this behavior (I know it was a big release).

**Comment by tsssplee** [comment]
Had same issues using Angular without Quill. Managed to find the problem. 

### Problem
It is due to zone.js in Angular not supporting AbortSignal in addEventListener. See [https://github.com/angular/angular/issues/49591](url) for reference. 

Mathlive uses many of these AbortSignal in src/virtual-keyboard/utils.ts

```typescript
  const controller = new AbortController();

  target.classList.add('is-pressed');
  target.addEventListener(
     #'pointerenter',
    handleVirtualKeyboardEvent(controller),
    {
      capture: true,
      signal: controller.signal,
    }
  );
  target.addEventListener(
    'pointerleave',
    handleVirtualKeyboardEvent(controller),
    {
      capture: true,
      signal: controller.signal,
    }
  );
  target.addEventListener(
    'pointercancel',
    handleVirtualKeyboardEvent(controller),
    {
      signal: controller.signal,
    }
  );
  target.addEventListener('pointerup', handleVirtualKeyboardEvent(controller), {
    signal: controller.signal,
  });
``` 

Managed to find 2 workarounds. Both not ideal.

### Workaround 1: Disable patching of event in zone.js
zone.js allows certain events to be unpatched through `__zone_symbol__UNPATCHED_EVENTS`. From zone.d.ts

<img width="668" alt="image" src="https://github.com/arnog/mathlive/assets/53547862/be44407d-cd30-4b33-9c2d-b093446a5a29">

In your angular project `polyfill.ts`

```typescript
import './zone-flags';
import 'zone.js';  // Included with Angular CLI.
```
then create the `zone-flags.ts` in the same directory as `polyfill.ts` with the contents

```typescript
(window as any).__zone_symbol__UNPATCHED_EVENTS = ["pointerup"];
```
See the comments in `polyfill.ts` why the zone flags must be in a separate file.
In my own testing, only `pointerup` event is needed although Mathlive uses many other events. Not sure this is true for your case.


_Caution_  I suppose doing this means **ALL** `pointerup` event handlers will be running outside of zone. Not sure how much it will affect the change detection in Angular.

### Workaround 2: Patch zone.js

With reference to the patch in [https://github.com/angular/angular/issues/49591#issuecomment-1483781992](url), make a copy of `zone.js` file, insert the 3 patch lines at the appropriate place, and place this file in the same directory as `polyfill.ts`. 

![image](https://github.com/arnog/mathlive/assets/53547862/dc8cbbf4-08d4-4d76-a6ba-96d02769c409)


Next instead of using the zone.js in `node_modules`, use your own copy by changing `polyfill.ts`

```typescript
import './zone.js';
// import 'zone.js';  // Included with Angular CLI.
```

_Caution_ You will need to do this every time you need to update zone.js library. Also not sure of the impact with Angular change detection.

**Comment by arnog** [comment]
Thanks @tsssplee for the detail writeup and explanation. That seems to be the problem, indeed. It also seems like this problem has now been fixed in zone.js/Angular, but I'm not sure in which version exactly. The workarounds you list are an option in the meantime.

**Comment by anisabboud** [comment]
@tsssplee Thank you for writing up the details of the issue and providing workarounds!

@arnog Where did you see that it was fixed in zone.js/Angular?
I'm still experiencing this issue in the latest version of Angular 16.0.2 with mathlive 0.94.0

**Comment by arnog** [comment]
@anisabboud the fix is here: https://github.com/JiaLiPassion/angular/commit/8a5183711e7b481b9071845e428f3992a1554b26

I don't know the deployment status of it, though.

**Comment by LinhTT46** [comment]
I'm still see this problem in the latest version of mathlive (0.94.6).
![Screenshot from 2023-06-13 08-21-26](https://github.com/arnog/mathlive/assets/44936298/a9c0d9a2-6cf9-4eac-a88e-34c8b0c62e1c)

Hi @anisabboud, which version did you see that it got fixed?

**Comment by anisabboud** [comment]
It's not fixed.

**Comment by LinhTT46** [comment]
Hi @arnog, please take a look at this bug. I'm using the latest version but it still exists

**Comment by arnog** [comment]
@LinhTT46 the bug is in Angular: https://github.com/angular/angular/issues/49591 I don't know when it will be fixed.

**Comment by anisabboud** [comment]
Update: Angular `zone.js` [`0.14.3`](https://github.com/angular/angular/releases/tag/zone.js-0.14.3) was released today which fixes the sticky buttons [issue](https://github.com/angular/angular/issues/49591).
